[package]
name = "cooky_importer"
version = "0.1.0"
edition = "2018"

[dependencies]
tracing-subscriber = "0.3.1"
anyhow = "1.0.70"
mdbook-linkcheck = "0.6.0"

[build-dependencies]
tonic-build = "0.6.0"